services:
  nacos:
    image: nacos/nacos-server:v2.3.0
    container_name: nacos-standalone
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    environment:
      - MODE=standalone
      - PREFER_HOST_MODE=hostname
    volumes:
      - nacos_logs:/home/nacos/logs
    restart: unless-stopped

volumes:
  nacos_logs: