server:
  port: 8080

spring:
  application:
    name: gateway-service
  profiles:
    active: debug
  main:
    web-application-type: reactive
  cloud:
    nacos:
      discovery:
        server-addr: nacos-server:8848
        locator:
          enabled: true
        enable-local-cache: false
      config:
        import-check:
          enabled: false
    # Spring Cloud Gateway 配置项，对应 GatewayProperties 类
    gateway:
      server:
        webflux:
          # 路由配置项，对应 RouteDefinition 数组
          routes:
            - id: user-service # 路由的编号
              # lb 表示负载均衡
              uri: lb://user-service # 路由到的目标地址
              predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
                - Path=/api/users/**
              filters:
                # 移除路径前缀
                - StripPrefix=0
            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/api/products/**
              filters:
                - StripPrefix=0

# JWT 配置
jwt:
  secret: ${JWT_SECRET:alicewasbeginningtogetverytiredofsittingbyhersisteronthebank}
  expiration: ${JWT_EXPIRATION:604800000}

# 日志配置
logging:
  level:
    '[org.springframework.cloud.gateway]': DEBUG
    '[top.otsuland.market]': DEBUG
    '[com.alibaba.nacos]': DEBUG
